### PR TITLE
Update to 13.38.1

### PR DESCRIPTION
**Pull request by Stell0**
https://github.com/NethServer/dev/issues/6386

### CODE REVIEW

**Review by gsanchietti — COMMENTED** [review]
I don't see any relevant change.

Are we hitting some issue with the current release?

**Comment by Stell0** [comment]
It's a security release

**Comment by gsanchietti** [comment]
The asterisk issue tracker is down, so I can't read the related issue: https://issues.asterisk.org/jira/browse/ASTERISK-29191
Reading the changelog, it doesn't seems a server issue.

Releasing a new asterisk version usually takes weeks, this is why I would like to avoid it, if not really necessary.

**Comment by gsanchietti** [comment]
The fix seems to prevent a crash of the server which could lead to a DOS attack.
Let's go with the release.

**Review by gsanchietti — APPROVED** [review]

**Pull request merged**
