### PR TITLE
Don't restart Asterisk on updates

### PR DESCRIPTION
**Pull request by Stell0**
https://github.com/NethServer/dev/issues/6749

### CODE REVIEW

**Review by gsanchietti — COMMENTED** [review]
This patch changes the behavior of existing package and breaks users expectation.
Why is it needed?

**Comment by Stell0** [comment]
It restores the Asterisk 13 behavior, it is needed because updates are kept automatic by policy also for critical customers and the restart of Asterisk could be problematic for them

**Comment by gsanchietti** [comment]
> It restores the Asterisk 13 behavior, it is needed because updates are kept automatic by policy also for critical customers and the restart of Asterisk could be problematic for them

We had 4 release in the last year with the restart: I don't get why it suddenly became a problem.

**Comment by andrea-marchionni** [comment]
> > It restores the Asterisk 13 behavior, it is needed because updates are kept automatic by policy also for critical customers and the restart of Asterisk could be problematic for them
> 
> We had 4 release in the last year with the restart: I don't get why it suddenly became a problem.

The problem has always been there since the release of version 18, we were probably just lucky that we didn't interrupt critical services with an update while on a phone call

**Comment by gsanchietti** [comment]
> > > It restores the Asterisk 13 behavior, it is needed because updates are kept automatic by policy also for critical customers and the restart of Asterisk could be problematic for them
> > 
> > 
> > We had 4 release in the last year with the restart: I don't get why it suddenly became a problem.
> 
> The problem has always been there since the release of version 18, we were probably just lucky that we didn't interrupt critical services with an update while on a phone call

So how the admin is notified about the update? Is the service restarted somewhere else?

**Comment by Stell0** [comment]
> So how the admin is notified about the update? Is the service restarted somewhere else?

On enterprise version, service is restarted by nethserver-nethvoice14 package update when there aren't active calls, on community the admin needs to keep issue tracker or yum log

**Comment by gsanchietti** [comment]
If the admin doesn't restart asterisk but tries to load a new module by changing a FreePBX configuration, the system will be have an inconsistent state: asterisk will try to load a module with a version different from the running core.

Usually  services are restarted after an RPM update, and asterisk should not behave differently.

I also do not see any enterprise-related PR to this issue.

**Comment by Stell0** [comment]
With this change, instead of restarting Asterisk using systemd, a "core restart when convenient" command is launched. With this command, Asterisk is restarted when there aren't ongoing calls

**Review by gsanchietti — APPROVED** [review]
The subshell should guarantee the background process.

**Pull request merged**
